arch:
  - arm32
  - arm64
  - amd64

language: elixir

elixir:
  - '1.7.4'
otp_release: '21.1.4'

services:
  - docker

before_install:
  - docker build -t signalbroker-server:latest -f ./docker/Dockerfile .
  # - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  # - docker ps -a
  # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - echo "testing disabled :)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag signalbroker-server:latest "$DOCKER_USERNAME"/signalbroker-server:travis-$TRAVIS_BUILD_NUMBER
  - docker push "$DOCKER_USERNAME"/signalbroker-server:travis-$TRAVIS_BUILD_NUMBER