arch:
  - arm64
  # - arm32 https://travis-ci.community/t/erlang-otp-21-1-4-is-missing-but-only-for-arm-64/6438/3
  - amd64

language: elixir

elixir:
  - 1.8.1

otp_release:
  - 22.0.5

services:
  - docker

before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix test --exclude ignore --exclude socketcan
  - mix clean
  - docker build -t signalbroker-server:latest -f ./docker/Dockerfile .
  # - echo "testing inside docker container..."
  # - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  # - docker ps -a
  # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Upload Container to DockerHub"; else travis_terminate 0; fi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag signalbroker-server:latest "$DOCKER_USERNAME"/signalbroker-server:travis-$TRAVIS_BUILD_NUMBER-$TRAVIS_CPU_ARCH
  - docker push "$DOCKER_USERNAME"/signalbroker-server:travis-$TRAVIS_BUILD_NUMBER-$TRAVIS_CPU_ARCH