# Author: Alvaro Rodrigo Alonso
# CDSID: aalonso
# Created: Dec 3 2019
# Volvo Car Corporation

version: '3.2'
services:
  signal-broker:
    tty: true
    ## Build and name the SB image
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: signalbroker:v1
    ## Network mode only available in Linux
    network_mode: "host"
    # # The following lines can be commented out if you need a custom configuration 
    # # This volume-mount is needed if you are going to modify the configuration files
    # volumes:
    #  - "${CONFIG_FOLDER:?Add CONFIG_FOLDER path to your .env file}:/signalbroker/_build/prod/rel/signal_server/configuration"
    # # Use this line only if you need a custom command to be executed by this image
    # # Define the your custom command in the .env file 
    # command: "${CUSTOM_COMMAND}"
