# Author: Alvaro Rodrigo Alonso
# CDSID: aalonso
# Created: Dec 3 2019
# Volvo Car Corporation

version: '3.2'
services:
  signal-broker:
    tty: true
    # Build and name the SB image
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: signalbroker:v1
    # Bridge mode for MacOS and WinOS
    network_mode: "bridge"
    # When bridge mode is used is more reliable to
    # specify the network interface.
    # Add DOCKER_HOST_IP=YOUR.IP to an .env file
    ports:
      - "${DOCKER_HOST_IP:?Add docker host IP}:4040:4040"
      - "${DOCKER_HOST_IP:?Add docker host IP}:50051:50051"
      - "${DOCKER_HOST_IP:?Add docker host IP}:2000:2000/udp"
      - "${DOCKER_HOST_IP:?Add docker host IP}:2001:2001/udp"
    # # The following lines can be commented out if you don't need a custom configuration 
    # # This volume-mount is only needed if you are going to modify the configuration files
    volumes:
      - "${CONFIG_FOLDER:?Add CONFIG_FOLDER path to your .env file}:/signalbroker/_build/prod/rel/signal_server/configuration"
    # # Use this line only if you need a custom command to be executed by this image
    # # Define the your custom command in the .env file 
    # command: "${CUSTOM_COMMAND}"
